#!/usr/bin/ruby
require 'io/console'

BLOCK = "\u2582"
EMPTY = " "
SIZE = IO.console.winsize
WIDTH = SIZE.last
HEIGHT = SIZE.first

def rand_bool(t = 1, f = 1); ([true]*t + [false]*f).sample; end;

def rand_line sleep = true
  WIDTH.times { |i| print rand_bool(1, 3) ? BLOCK : EMPTY }
  sleep 0.1 if sleep
end

HEIGHT.times { rand_line false }
rand_line while true
